opengeospatial/ets-ogcapi-features10

pom.xml, src/main/java/org/opengis/cite/wfs30/CommonFixture.java, src/main/java/org/opengis/cite/wfs30/SuiteAttribute.java, src/main/java/org/opengis/cite/wfs30/SuiteFixtureListener.java, src/main/java/org/opengis/cite/wfs30/TestFailureListener.java, src/main/java/org/opengis/cite/wfs30/WFS3.java, src/main/java/org/opengis/cite/wfs30/apidescription/ApiDefinition.java, src/main/java/org/opengis/cite/wfs30/apidescription/LandingPage.java, src/main/resources/org/opengis/cite/wfs30/testng.xml, src/test/java/org/opengis/cite/wfs30/apidescription/ApiDefinitionIT.java, src/test/java/org/opengis/cite/wfs30/apidescription/LandingPageIT.java
=> Implemented ATS A.4.2

src/main/java/org/opengis/cite/wfs30/WFS3.java, src/main/java/org/opengis/cite/wfs30/apidescription/OpenApi.java, src/main/java/org/opengis/cite/wfs30/collections/FeatureCollectionsMetadataOperation.java, src/main/java/org/opengis/cite/wfs30/conformance/ConformanceOperation.java, src/main/java/org/opengis/cite/wfs30/openapi3/OpenApiUtils.java, src/main/java/org/opengis/cite/wfs30/openapi3/TestPoint.java, src/main/resources/org/opengis/cite/wfs30/testng.xml, src/test/java/org/opengis/cite/wfs30/collections/FeatureCollectionsMetadataOperationIT.java, src/test/java/org/opengis/cite/wfs30/conformance/ConformanceOperationIT.java, src/test/java/org/opengis/cite/wfs30/openapi3/OpenApiUtilsTest.java, src/test/resources/org/opengis/cite/wfs30/collections/collections.json
=> Implemented A.4.4 Part 2

src/main/java/org/opengis/cite/wfs30/collections/FeatureCollectionsMetadataOperation.java, src/test/java/org/opengis/cite/wfs30/collections/FeatureCollectionsMetadataOperationIT.java
=> Removed assert from test validateFeatureCollectionsMetadataOperationResponse_Collections

src/main/java/org/opengis/cite/wfs30/collections/GetFeaturesOperation.java, src/main/java/org/opengis/cite/wfs30/openapi3/OpenApiUtils.java, src/test/java/org/opengis/cite/wfs30/collections/GetFeaturesOperationIT.java, src/test/java/org/opengis/cite/wfs30/openapi3/OpenApiUtilsTest.java
=> Implemented data provider for all collections paths

src/main/config/test-run-props.xml, src/main/java/org/opengis/cite/wfs30/CommonDataFixture.java, src/main/java/org/opengis/cite/wfs30/SuiteAttribute.java, src/main/java/org/opengis/cite/wfs30/SuiteFixtureListener.java, src/main/java/org/opengis/cite/wfs30/TestRunArg.java, src/main/java/org/opengis/cite/wfs30/WFS3.java, src/main/java/org/opengis/cite/wfs30/collections/FeatureCollectionsMetadataOperation.java, src/main/java/org/opengis/cite/wfs30/collections/GetFeatureOperation.java, src/main/java/org/opengis/cite/wfs30/collections/GetFeaturesOperation.java, src/main/java/org/opengis/cite/wfs30/conformance/ConformanceOperation.java, src/main/java/org/opengis/cite/wfs30/openapi3/OpenApiUtils.java, src/main/java/org/opengis/cite/wfs30/util/JsonUtils.java, src/main/resources/test-run-props.xml, src/main/scripts/ctl/wfs30-suite.ctl, src/test/java/org/opengis/cite/wfs30/openapi3/OpenApiUtilsTest.java, src/test/java/org/opengis/cite/wfs30/util/JsonUtilsIT.java
=> Reduce number of requests

pom.xml
=> Updated docker configuration.

src/main/java/org/opengis/cite/wfs30/collections/GetFeatureOperation.java
See #54 
Waiting for review
Closes #54
=> Manage when no query params in URL (see #54)

src/main/java/org/opengis/cite/wfs30/openapi3/OpenApiUtils.java, src/test/java/org/opengis/cite/wfs30/openapi3/OpenApiUtilsTest.java
=> Fixed IndexOutOfBoundsException

src/main/javadoc/overview.html, src/site/asciidoc/index.adoc
=> Added documentation of the parameter noofcollections

src/site/asciidoc/index.adoc
=> Fix documentation of preconditions

src/main/java/org/opengis/cite/wfs30/util/JsonUtils.java
=> Allow other data types than String in parseFeatureId

src/main/java/org/opengis/cite/wfs30/collections/GetFeaturesOperation.java
=> Rename time parameter 65

src/main/java/org/opengis/cite/ogcapifeatures10/apidefinition/ApiDefinition.java, src/main/java/org/opengis/cite/ogcapifeatures10/openapi3/OpenApiUtils.java, src/test/java/org/opengis/cite/ogcapifeatures10/openapi3/OpenApiUtilsTest.java, src/test/resources/org/opengis/cite/ogcapifeatures10/openapi3/openapi-relativeServerPath.json
=> Support of relative server urls

pom.xml, src/test/java/org/opengis/cite/ogcapifeatures10/openapi3/OpenApiUtilsTest.java
=> Updated openapi-parser to 4.0.4

pom.xml, src/main/java/org/opengis/cite/ogcapifeatures10/collections/FeaturesErrorConditions.java, src/main/java/org/opengis/cite/ogcapifeatures10/openapi3/OpenApiUtils.java, src/test/java/org/opengis/cite/ogcapifeatures10/collections/FeaturesErrorConditionsTest.java, src/test/java/org/opengis/cite/ogcapifeatures10/openapi3/OpenApiUtilsTest.java, src/test/resources/org/opengis/cite/ogcapifeatures10/openapi3/openapi-freeformparam.json
=> Improved test unknownQueryParameter

src/main/java/org/opengis/cite/ogcapifeatures10/apidefinition/ApiDefinition.java
=> Updated the test openapiDocumentRetrieval to fail if null.

src/main/java/org/opengis/cite/ogcapifeatures10/collections/FeaturesAssertions.java
=> Removed timestamp assertion.

pom.xml
=> Updated Javadoc source in pom file.

src/assembly/ctl-scripts.xml
=> Fixed error in build output by updating the assembly file.

pom.xml, src/main/java/org/opengis/cite/ogcapifeatures10/util/JsonUtils.java
Fixes https://github.com/opengeospatial/ets-ogcapi-features10/issues/111
=> Fix for Javadoc JDK version issue at build

src/main/java/org/opengis/cite/ogcapifeatures10/conformance/Conformance.java
=> Updated the test to throw exception if data provider is empty.

src/main/java/org/opengis/cite/ogcapifeatures10/collections/FeaturesLimit.java
=> Updated condition to set limit for validateFeaturesWithLimitOperation test.

src/main/java/org/opengis/cite/ogcapifeatures10/collections/FeaturesErrorConditions.java, src/main/java/org/opengis/cite/ogcapifeatures10/openapi3/OpenApiUtils.java, src/test/java/org/opengis/cite/ogcapifeatures10/openapi3/OpenApiUtilsTest.java
=> Fixed API path issue.

src/main/java/org/opengis/cite/ogcapifeatures10/CommandLineArguments.java, src/main/java/org/opengis/cite/ogcapifeatures10/TestNGController.java, src/main/scripts/ctl/ogcapi-features-1.0-suite.ctl, src/site/asciidoc/how-to-run-the-tests.adoc
=> Updated test suite which will accept CMD parameter to enabled default listner to generate HTML report.

src/main/java/org/opengis/cite/ogcapifeatures10/collections/FeaturesErrorConditions.java, src/test/java/org/opengis/cite/ogcapifeatures10/collections/FeaturesErrorConditionsTest.java
=> fix typo in function name

src/main/java/org/opengis/cite/ogcapifeatures10/collections/FeatureCollections.java
=> Added check to collect collections on basis of itemType and items.

src/main/java/org/opengis/cite/ogcapifeatures10/apidefinition/ApiDefinition.java, src/main/java/org/opengis/cite/ogcapifeatures10/collections/AbstractFeatures.java, src/main/java/org/opengis/cite/ogcapifeatures10/collections/Feature.java
=> Updated test suite to handle relative links.

src/main/java/org/opengis/cite/ogcapifeatures10/collections/Feature.java
=> Updated test suite to handle ".{extension}" path.

src/main/java/org/opengis/cite/ogcapifeatures10/apidefinition/ApiDefinition.java, src/main/java/org/opengis/cite/ogcapifeatures10/collections/Feature.java, src/main/java/org/opengis/cite/ogcapifeatures10/collections/FeatureCollections.java, src/main/java/org/opengis/cite/ogcapifeatures10/collections/FeaturesAssertions.java, src/main/java/org/opengis/cite/ogcapifeatures10/collections/FeaturesLimit.java, src/main/java/org/opengis/cite/ogcapifeatures10/util/JsonUtils.java
=> Fixed possible null pointer exceptions

src/main/java/org/opengis/cite/ogcapifeatures10/conformance/core/collections/FeaturesTime.java, src/main/java/org/opengis/cite/ogcapifeatures10/conformance/core/conformance/Conformance.java, src/main/java/org/opengis/cite/ogcapifeatures10/conformance/core/landingpage/LandingPage.java
=> Fixed java doc

pom.xml, src/main/java/org/opengis/cite/ogcapifeatures10/EtsAssert.java, src/main/java/org/opengis/cite/ogcapifeatures10/conformance/core/collections/AbstractFeatures.java, src/main/java/org/opengis/cite/ogcapifeatures10/conformance/core/collections/Features.java, src/main/java/org/opengis/cite/ogcapifeatures10/conformance/core/collections/FeaturesBBox.java, src/main/java/org/opengis/cite/ogcapifeatures10/conformance/core/collections/FeaturesLimit.java, src/main/java/org/opengis/cite/ogcapifeatures10/conformance/core/collections/FeaturesTime.java, src/test/java/org/opengis/cite/ogcapifeatures10/EtsAssertTest.java
=> Implemented Abstract Test2

src/main/java/org/opengis/cite/ogcapifeatures10/EtsAssert.java, src/main/java/org/opengis/cite/ogcapifeatures10/conformance/core/collections/FeatureCollections.java, src/test/java/EtsAssertTest.java
=> Implemented Abstract Test 10, Test Method 3

src/main/java/org/opengis/cite/ogcapifeatures10/conformance/crs/query/bboxcrs/AbstractBBoxCrs.java, src/main/java/org/opengis/cite/ogcapifeatures10/conformance/crs/query/bboxcrs/BBoxCrsParameter.java
=> Closes #199

src/main/java/org/opengis/cite/ogcapifeatures10/conformance/core/collections/Feature.java, src/site/asciidoc/index.adoc
=> Closes #215

src/main/java/org/opengis/cite/ogcapifeatures10/OgcApiFeatures10.java, src/main/java/org/opengis/cite/ogcapifeatures10/conformance/core/collections/FeatureCollections.java, src/main/java/org/opengis/cite/ogcapifeatures10/conformance/crs/discovery/collection/DiscoveryCollectionCrsUri.java, src/main/java/org/opengis/cite/ogcapifeatures10/conformance/crs/query/crs/features/AbstractFeaturesCrs.java, src/main/java/org/opengis/cite/ogcapifeatures10/openapi3/OpenApiUtils.java, src/main/java/org/opengis/cite/ogcapifeatures10/util/JsonUtils.java, src/site/asciidoc/index.adoc, src/test/java/org/opengis/cite/ogcapifeatures10/openapi3/OpenApiUtilsTest.java
=> Closes #202

src/main/java/org/opengis/cite/ogcapifeatures10/conformance/crs/query/crs/feature/FeatureCrsParameterTransform.java, src/main/java/org/opengis/cite/ogcapifeatures10/openapi3/UriBuilder.java
=> Closes #201

src/main/java/org/opengis/cite/ogcapifeatures10/openapi3/UriBuilder.java
(cherry picked from commit 3f269437cdde3fe9b1f01e5545fa560a58f0ec65)
Closes #177
=> Closes #177

src/main/java/org/opengis/cite/ogcapifeatures10/conformance/crs/query/crs/feature/FeatureCrsParameter.java, src/main/java/org/opengis/cite/ogcapifeatures10/conformance/crs/query/crs/features/FeaturesCrsParameter.java
=> Closes #200

src/main/java/org/opengis/cite/ogcapifeatures10/conformance/core/apidefinition/ApiDefinition.java
=> Closing #198

src/main/java/org/opengis/cite/ogcapifeatures10/conformance/core/collections/FeaturesAssertions.java, src/main/java/org/opengis/cite/ogcapifeatures10/conformance/core/collections/FeaturesLimit.java
=> Closing #196

src/main/java/org/opengis/cite/ogcapifeatures10/conformance/core/collections/FeaturesAssertions.java, src/main/java/org/opengis/cite/ogcapifeatures10/conformance/core/collections/FeaturesLimit.java
=> Closing #195

src/main/java/org/opengis/cite/ogcapifeatures10/conformance/core/apidefinition/ApiDefinition.java
=> Closing #176

src/docker/Dockerfile
10 layers in output image reduced to 2.. I cannot test this
=> Update Dockerfile; reducec number of layers

src/main/java/org/opengis/cite/ogcapifeatures10/conformance/CommonFixture.java, src/main/java/org/opengis/cite/ogcapifeatures10/conformance/core/collections/FeatureCollection.java, src/main/java/org/opengis/cite/ogcapifeatures10/conformance/core/collections/FeatureCollections.java, src/main/java/org/opengis/cite/ogcapifeatures10/conformance/core/collections/FeaturesBBox.java, src/test/java/org/opengis/cite/ogcapifeatures10/conformance/core/collections/FeatureCollectionTest.java
=> Closes #222

src/main/java/org/opengis/cite/ogcapifeatures10/OgcApiFeatures10.java, src/main/java/org/opengis/cite/ogcapifeatures10/conformance/crs/discovery/collection/DiscoveryCollectionDefaultCrs.java
=> Closes #221

src/main/java/org/opengis/cite/ogcapifeatures10/conformance/core/collections/AbstractFeatures.java, src/main/java/org/opengis/cite/ogcapifeatures10/conformance/core/collections/FeaturesBBox.java
=> Closes #247

src/main/java/org/opengis/cite/ogcapifeatures10/conformance/core/collections/AbstractFeatures.java
=> Closes #241

src/main/resources/proj4/nad/epsg
=> Closes #245
